<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>io.github.patton174</groupId>
        <artifactId>coco-parent</artifactId>
        <version>${revision}</version>
        <relativePath>../../../../../../coco-parent/pom.xml</relativePath>
    </parent>

    <groupId>com.example</groupId>
    <artifactId>different-business-version</artifactId>
    <version>99.7.3</version>

    <dependencies>
        <dependency>
            <groupId>io.github.patton174</groupId>
            <artifactId>coco-audit-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.patton174</groupId>
            <artifactId>coco-replay-redis</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.patton174</groupId>
            <artifactId>coco-rate-limit</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.patton174</groupId>
            <artifactId>coco-observability</artifactId>
        </dependency>
    </dependencies>
</project>
