package io.github.coco.feature.web.trace;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;

import java.util.Map;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicReference;

import io.github.coco.context.CocoRequestContext;
import io.github.coco.context.CocoRequestContextAttributes;
import io.github.coco.context.CocoRequestContextHolder;
import io.github.coco.context.trace.CocoTraceContext;
import io.github.coco.feature.web.context.CocoWebRequestSnapshot;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Test;
import org.slf4j.MDC;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

/**
 * {@link CocoTraceFilter} 单元测试。
 *
 * @author patton174
 * @since 1.0.0
 */
class CocoTraceFilterTest {

    @AfterEach
    void clearContext() {
        CocoRequestContextHolder.clear();
        CocoTraceContext.clear();
    }

    @Test
    void traceIdFromHeaderAppearsInResponseAndContext() throws Exception {
        CocoTraceProperties properties = new CocoTraceProperties();
        CocoTraceFilter filter = new CocoTraceFilter(properties, java.util.List.of(),
                new io.github.coco.feature.web.accesslog.CocoAccessLogCaptureProperties(),
                (traceId, request) -> baseSnapshot(traceId));
        MockHttpServletRequest request = new MockHttpServletRequest("GET", "/api/test");
        request.addHeader(properties.getHeaderName(), "custom-trace-id");
        MockHttpServletResponse response = new MockHttpServletResponse();
        AtomicReference<CocoRequestContext> context = new AtomicReference<>();

        filter.doFilter(request, response,
                (req, res) -> context.set(CocoRequestContextHolder.current().orElseThrow()));

        assertEquals("custom-trace-id", response.getHeader(properties.getHeaderName()));
        assertEquals("custom-trace-id", context.get().traceId());
    }

    @Test
    void autoGeneratedTraceIdWhenNoHeader() throws Exception {
        CocoTraceProperties properties = new CocoTraceProperties();
        CocoTraceFilter filter = new CocoTraceFilter(properties, java.util.List.of(),
                new io.github.coco.feature.web.accesslog.CocoAccessLogCaptureProperties(),
                (traceId, request) -> baseSnapshot(traceId));
        MockHttpServletRequest request = new MockHttpServletRequest("GET", "/api/test");
        MockHttpServletResponse response = new MockHttpServletResponse();
        AtomicReference<CocoRequestContext> context = new AtomicReference<>();

        filter.doFilter(request, response,
                (req, res) -> context.set(CocoRequestContextHolder.current().orElseThrow()));

        String traceId = response.getHeader(properties.getHeaderName());
        assertNotNull(traceId);
        assertFalse(traceId.isBlank());
        assertEquals(traceId, context.get().traceId());
    }

    @Test
    void contextCleanedUpAfterFilterCompletes() throws Exception {
        CocoTraceProperties properties = new CocoTraceProperties();
        CocoTraceFilter filter = new CocoTraceFilter(properties, java.util.List.of(),
                new io.github.coco.feature.web.accesslog.CocoAccessLogCaptureProperties(),
                (traceId, request) -> baseSnapshot(traceId));
        MockHttpServletRequest request = new MockHttpServletRequest("GET", "/api/test");
        request.addHeader(properties.getHeaderName(), "trace-cleanup-test");

        filter.doFilter(request, new MockHttpServletResponse(), (req, res) -> {});

        assertEquals(Optional.empty(), CocoRequestContextHolder.current());
        assertNull(MDC.get(properties.getMdcKey()));
    }

    private static CocoWebRequestSnapshot baseSnapshot(String traceId) {
        return new CocoWebRequestSnapshot(traceId, "GET", "/api/test", null, "127.0.0.1",
                null, null, "http", "localhost", 80, null, Map.of(), Map.of())
                .withContextAttribute(CocoRequestContextAttributes.CLIENT_IP, "127.0.0.1");
    }
}