package io.github.coco.maven;

import static org.assertj.core.api.Assertions.assertThat;

import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;
import javax.xml.parsers.DocumentBuilderFactory;
import javax.xml.xpath.XPathConstants;
import javax.xml.xpath.XPathFactory;

import org.junit.jupiter.api.Test;
import org.w3c.dom.Document;
import org.w3c.dom.Node;
import org.w3c.dom.NodeList;

/**
 * Coco Maven 插件描述符测试。
 * <p>
 * 锁定插件对外暴露的 goal 集合。插件描述符由 maven-plugin-plugin 在 {@code process-classes} 阶段生成，
 * 是业务项目真正能调用的契约，因此这里断言的是构建产物而不是源码。3.0.0 移除的 {@code coco:generate}
 * 一旦被重新引入，或现有 goal 被改名、漏掉，本测试都会失败。
 * </p>
 * <p>
 * 项目信息：
 * </p>
 * <ul>
 *   <li>作者：<a href="https://github.com/patton174">patton174</a></li>
 *   <li>仓库：<a href="https://github.com/patton174/coco-framework">https://github.com/patton174/coco-framework</a></li>
 *   <li>模块：{@code coco-maven-plugin}</li>
 * </ul>
 * @author patton174
 * @since 3.0.0
 */
class CocoMavenPluginDescriptorTest {

    @Test
    void exposesOnlyTheFeatureAssemblyAndPruningGoals() throws Exception {
        assertThat(declaredGoals()).containsExactlyInAnyOrder("features", "prune-package");
    }

    @Test
    void doesNotExposeTheRetiredGenerateGoal() throws Exception {
        assertThat(declaredGoals()).doesNotContain("generate");
    }

    private List<String> declaredGoals() throws Exception {
        Path descriptor = Path.of(System.getProperty("basedir", "."))
                .toAbsolutePath()
                .resolve("target/classes/META-INF/maven/plugin.xml");
        assertThat(descriptor)
                .as("plugin descriptor generated by maven-plugin-plugin")
                .isRegularFile();

        DocumentBuilderFactory factory = DocumentBuilderFactory.newInstance();
        factory.setFeature("http://apache.org/xml/features/disallow-doctype-decl", true);
        factory.setFeature("http://xml.org/sax/features/external-general-entities", false);
        factory.setFeature("http://xml.org/sax/features/external-parameter-entities", false);
        Document document;
        try (InputStream input = Files.newInputStream(descriptor)) {
            document = factory.newDocumentBuilder().parse(input);
        }
        NodeList goals = (NodeList) XPathFactory.newInstance().newXPath().evaluate(
                "/plugin/mojos/mojo/goal/text()", document, XPathConstants.NODESET);
        List<String> declared = new ArrayList<>();
        for (int index = 0; index < goals.getLength(); index++) {
            declared.add(((Node) goals.item(index)).getTextContent().trim());
        }
        return declared;
    }
}
